receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource/service-name:
    attributes:
      - key: service.name
        value: QuentinXHugo
        action: upsert
  batch: {}

exporters:
  logging:
    loglevel: info
  otlphttp/jaeger:
    endpoint: https://jaeger-http.devonn.io/

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource/service-name, batch]
      exporters: [logging, otlphttp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
