services:
  gatling:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatling-sample
    volumes:
      # Monte le répertoire de résultats du conteneur vers le répertoire result du projet
      - ./result:/opt/gatling/results
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080}
      - API_URI=${API_URI:-/actuator/health}
      - USERS=${USERS:-10}
      - DURATION_SECONDS=${DURATION_SECONDS:-30}
    # Permet d'accéder aux services sur le réseau Docker si nécessaire
    network_mode: host

