logging.structured.ecs.service.name=RoyaumeQuestOrchestrator
logging.structured.ecs.service.version=1
logging.structured.ecs.service.environment=Production
logging.structured.ecs.service.node-name=Primary
