logging.file.name=logs/royaume-quests.log
logging.structured.format=ecs
logging.structured.console.enabled=false
logging.structured.file.enabled=true
logging.structured.ecs.service.name=RoyaumeQuestOrchestrator
logging.structured.ecs.service.version=1
logging.structured.ecs.service.environment=Production
logging.structured.ecs.service.node-name=Primary
