spring:
  application:
    name: QuentinXHugo
  datasource:
    url: jdbc:h2:mem:royaume;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

royaume:
  ihm:
    group: observabilia
    fake-api: false
    url: http://localhost:8080
  professor:
    base-url: https://royaume.devonn.io
    group: observabilia
    fetch-delay: 15s
    processing-delay: 5s

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.95,0.99
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_TRACES_EXPORTER_ENDPOINT}
    metrics:
      export:
        enabled: true
        url: ${OTEL_METRICS_EXPORTER_ENDPOINT}

logging:
  file:
    name: ${LOG_FILE:logs/royaume-quests.json}
