input {
  beats {
    port => 5044
  }
}

filter {
  if [@metadata][beat] {
    mutate {
      add_field => { "ingested_by" => "%{[@metadata][beat]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "royaume-quests-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
